[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[general]
live_config_reload = true

[colors.bright]
black = "#535551"
blue = "#6f9bca"
cyan = "#32dddd"
green = "#87dd32"
magenta = "#a97ca4"
red = "#ea2828"
white = "#e9e9e7"
yellow = "#f7e44d"

[colors.normal]
black = "#393939"
blue = "#5778c1"
cyan = "#6eb5f3"
green = "#96a967"
magenta = "#9c35ac"
red = "#ca674a"
white = "#a9a9a9"
yellow = "#d3a94a"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold"

[font.italic]
style = "Regular"

[font.normal]
family = "Iosevka"
style = "Medium"

[keyboard]

[window]
decorations = "none"
option_as_alt = "Both"
